/* GENERATED BY REDUX-GENERATOR */
const TYPE = "TYPE_REPLACE"

class Action {
  static elements(element) {
    return {
      type: TYPE,
      value: element
    }
  }
}

export default Action;
export { TYPE };